-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Playerstats CASCADE;
DROP TABLE IF EXISTS Playergame CASCADE;
DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS Game CASCADE;
